# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: diplom
      POSTGRES_USER: diplom
    volumes:
      - type: bind
        source: ./dbdata
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:8081
    environment:
      PGADMIN_DEFAULT_EMAIL: s.shishkov2026@gmail.com
      PGADMIN_DEFAULT_PASSWORD: diplom


